version: 0.2
 
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
      - pip install docker-compose
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - echo Writing image definitions file...
      - printf '[{"environment":[{"name":"WORDPRESS_DB_USER","value":"wpuser"},{"name":"WORDPRESS_DB_PASSWORD","value":"wppass"},{"name":"WORDPRESS_DB_NAME","value":"wpdb"}],"name":"wp","image":"wordpress:latest","cpu":100,"portMappings":[{"containerPort":80,"hostPort":80}],"links":["mysql:mysql"],"memory":1024,"essential":false},{"environment":[{"name":"MYSQL_ROOT_PASSWORD","value":"rootwppass"},{"name":"MYSQL_USER","value":"wpuser"},{"name":"MYSQL_PASSWORD","value":"wppass"},{"name":"MYSQL_DATABASE","value":"wpdb"}],"name":"mysql","image":"mysql","cpu":200,"memory":2048,"essential":true}]' > imagedefinitions.json

artifacts:
    files: imagedefinitions.json
